import type { PublicSnapshotRows } from '../../types/content.ts';

type FieldRule = 'text' | 'uuid' | 'instant' | 'date' | 'integer' | 'boolean';
export type ColumnRule = `${FieldRule}${'' | '?'}`;
type RowRules = {
  [K in keyof PublicSnapshotRows]: { [F in keyof PublicSnapshotRows[K]]: ColumnRule };
};

/** Explicit RPC v1 contract. Validate PostgreSQL output at the network boundary. */
export const snapshotRowRules = {
  settings: {
    id: 'uuid',
    site_name: 'text',
    brand_short: 'text',
    professional_title: 'text?',
    hero_title: 'text?',
    hero_subtitle: 'text?',
    hero_description: 'text?',
    availability_enabled: 'boolean',
    availability_text: 'text?',
    location_public: 'text?',
    cv_url: 'text?',
    default_seo_title: 'text?',
    default_seo_description: 'text?',
    default_og_image: 'text?',
    default_og_image_asset_id: 'uuid?',
    about_summary_markdown: 'text?',
    about_profile_markdown: 'text?',
    working_method_markdown: 'text?',
    about_image_asset_id: 'uuid?',
    canonical_base: 'text?',
    robots_policy: 'text',
    timezone: 'text',
  },
  contact: {
    id: 'uuid',
    email: 'text?',
    whatsapp_number: 'text?',
    whatsapp_default_message: 'text?',
    cta_title: 'text?',
    cta_description: 'text?',
    form_enabled: 'boolean',
    cv_enabled: 'boolean',
    email_visible: 'boolean',
    whatsapp_visible: 'boolean',
    whatsapp_cta_label: 'text?',
  },
  social_links: {
    id: 'uuid',
    platform: 'text',
    label: 'text',
    url: 'text',
    icon: 'text?',
    sort_order: 'integer',
    visible: 'boolean',
  },
  projects: {
    id: 'uuid',
    title: 'text',
    slug: 'text',
    subtitle: 'text?',
    summary: 'text?',
    problem: 'text?',
    objective: 'text?',
    solution: 'text?',
    architecture: 'text?',
    challenges: 'text?',
    learnings: 'text?',
    role: 'text?',
    year: 'integer?',
    status: 'text',
    featured_image_url: 'text?',
    cover_image_url: 'text?',
    github_url: 'text?',
    demo_url: 'text?',
    documentation_url: 'text?',
    featured: 'boolean',
    published: 'boolean',
    seo_title: 'text?',
    seo_description: 'text?',
    og_image_url: 'text?',
    published_at: 'instant?',
    canonical_url: 'text?',
    robots_policy: 'text?',
    before_markdown: 'text?',
    after_markdown: 'text?',
    sort_order: 'integer',
    featured_image_asset_id: 'uuid?',
    cover_image_asset_id: 'uuid?',
    og_image_asset_id: 'uuid?',
  },
  project_features: {
    id: 'uuid',
    project_id: 'uuid',
    title: 'text',
    description: 'text?',
    icon: 'text?',
    sort_order: 'integer',
  },
  project_images: {
    id: 'uuid',
    project_id: 'uuid',
    asset_id: 'uuid',
    public_url: 'text?',
    alt_text: 'text',
    caption: 'text?',
    sort_order: 'integer',
    featured: 'boolean',
  },
  project_metrics: {
    id: 'uuid',
    project_id: 'uuid',
    value: 'text',
    label: 'text',
    description: 'text?',
    sort_order: 'integer',
    visible: 'boolean',
  },
  project_challenges: {
    id: 'uuid',
    project_id: 'uuid',
    title: 'text',
    problem: 'text?',
    solution: 'text?',
    sort_order: 'integer',
  },
  project_technologies: {
    project_id: 'uuid',
    technology_id: 'uuid',
    sort_order: 'integer',
  },
  posts: {
    id: 'uuid',
    title: 'text',
    slug: 'text',
    excerpt: 'text?',
    content_markdown: 'text',
    featured_image_url: 'text?',
    status: 'text',
    featured: 'boolean',
    reading_time: 'integer?',
    seo_title: 'text?',
    seo_description: 'text?',
    og_image_url: 'text?',
    published_at: 'instant?',
    canonical_url: 'text?',
    robots_policy: 'text?',
    popular_rank: 'integer?',
    featured_image_asset_id: 'uuid?',
    og_image_asset_id: 'uuid?',
  },
  categories: {
    id: 'uuid',
    name: 'text',
    slug: 'text',
    description: 'text?',
    sort_order: 'integer',
    visible: 'boolean',
  },
  post_category_relations: {
    post_id: 'uuid',
    category_id: 'uuid',
  },
  tags: {
    id: 'uuid',
    name: 'text',
    slug: 'text',
  },
  post_tags: {
    post_id: 'uuid',
    tag_id: 'uuid',
  },
  experiences: {
    id: 'uuid',
    position: 'text',
    organization: 'text',
    organization_url: 'text?',
    start_date: 'date',
    end_date: 'date?',
    current: 'boolean',
    summary: 'text?',
    description_markdown: 'text?',
    visible: 'boolean',
    sort_order: 'integer',
  },
  experience_highlights: {
    id: 'uuid',
    experience_id: 'uuid',
    title: 'text',
    description: 'text?',
    sort_order: 'integer',
  },
  experience_projects: {
    experience_id: 'uuid',
    project_id: 'uuid',
  },
  experience_technologies: {
    experience_id: 'uuid',
    technology_id: 'uuid',
  },
  technologies: {
    id: 'uuid',
    name: 'text',
    slug: 'text',
    category: 'text',
    description: 'text?',
    icon: 'text?',
    icon_url: 'text?',
    icon_asset_id: 'uuid?',
    official_url: 'text?',
    featured: 'boolean',
    visible: 'boolean',
    sort_order: 'integer',
  },
  specialties: {
    id: 'uuid',
    title: 'text',
    slug: 'text',
    description: 'text?',
    icon: 'text?',
    sort_order: 'integer',
    visible: 'boolean',
  },
  principles: {
    id: 'uuid',
    number: 'integer',
    title: 'text',
    description: 'text?',
    sort_order: 'integer',
    visible: 'boolean',
  },
  impact_metrics: {
    id: 'uuid',
    value: 'text',
    label: 'text',
    description: 'text?',
    sort_order: 'integer',
    visible: 'boolean',
  },
  media_assets: {
    id: 'uuid',
    public_url: 'text?',
    filename: 'text',
    mime_type: 'text',
    file_size: 'integer',
    width: 'integer?',
    height: 'integer?',
    alt_text: 'text?',
    caption: 'text?',
    category: 'text',
    visibility: 'text',
    decorative: 'boolean',
  },
  media_references: {
    asset_id: 'uuid',
    entity_type: 'text?',
    entity_id: 'uuid?',
    field: 'text',
  },
  documents: {
    id: 'uuid',
    type: 'text',
    title: 'text',
    asset_id: 'uuid',
    public_url: 'text?',
    active: 'boolean',
  },
} as const satisfies RowRules;
