-- F7 transactions run under actual Postgres roles, independent of every UI guard.
begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create function pg_temp.id(label text) returns uuid language sql immutable as $$select md5('f7-transaction-test:'||label)::uuid$$;
create function pg_temp.login(label text) returns void language sql as $$select set_config('request.jwt.claim.sub',pg_temp.id(label)::text,true)::void$$;
insert into auth.users(id) values(pg_temp.id('owner')),(pg_temp.id('inactive')),(pg_temp.id('normal'));
insert into public.admin_profiles(id,display_name,active) values(pg_temp.id('owner'),'F7 test owner',true),(pg_temp.id('inactive'),'F7 test inactive',false);
select ok(not exists(select 1 from pg_proc where proname in ('save_project','save_post','save_experience','touch_editorial_parent') and prosecdef),'F7 adds no SECURITY DEFINER');
select ok(not exists(select 1 from pg_proc where proname in ('save_project','save_post','save_experience','touch_editorial_parent') and not('search_path=""'=any(proconfig))),'Every F7 function has a fixed empty search_path');
set local role anon;
select throws_ok($q$select public.save_project(pg_temp.id('project'),null,'{}')$q$,'42501',null,'Anon cannot execute project writes');
select throws_ok($q$select public.save_post(pg_temp.id('post'),null,'{}')$q$,'42501',null,'Anon cannot execute post writes');
select throws_ok($q$select public.save_experience(pg_temp.id('experience'),null,'{}')$q$,'42501',null,'Anon cannot execute experience writes');
set local role authenticated;
select pg_temp.login('normal');
select throws_ok($q$select public.save_project(pg_temp.id('project'),null,'{}')$q$,'42501',null,'Authenticated is not administrator');
select throws_ok($q$select public.save_post(pg_temp.id('post'),null,'{}')$q$,'42501',null,'Noowner post write denied');
select throws_ok($q$select public.save_experience(pg_temp.id('experience'),null,'{}')$q$,'42501',null,'Noowner experience write denied');
select pg_temp.login('inactive');
select throws_ok($q$select public.save_project(pg_temp.id('project'),null,'{}')$q$,'42501',null,'Inactive owner write denied');
select pg_temp.login('owner');
select lives_ok($q$select public.save_project(pg_temp.id('project'),null,'{"title":"CMS fixture","slug":"cms-fixture"}',jsonb_build_object('features',jsonb_build_array(jsonb_build_object('id',pg_temp.id('feature'),'title','Atomic feature'))))$q$,'Owner creates parent and child in one transaction');
select is((select count(*) from public.project_features where project_id=pg_temp.id('project')),1::bigint,'Child persisted');
select throws_ok($q$select public.save_project(pg_temp.id('project'),null,'{"title":"Overwritten"}')$q$,'PT409',null,'Retry cannot overwrite an existing revision');
select throws_ok($q$select public.save_project(pg_temp.id('project'),'2000-01-01','{"title":"Stale"}')$q$,'PT409',null,'Stale timestamp rejected');
select throws_ok($q$select public.save_project(pg_temp.id('project'),(select updated_at from public.projects where id=pg_temp.id('project')),'{"title":"Should rollback"}','{"features":[{"title":""}]}')$q$,'23514',null,'Invalid child rolls back full transaction');
select is((select title from public.projects where id=pg_temp.id('project')),'CMS fixture','Parent title unchanged after child failure');
select is((select count(*) from public.project_features where project_id=pg_temp.id('project')),1::bigint,'Original child survives transaction rollback');
select throws_ok($q$select public.save_project(pg_temp.id('bad'),null,'{"title":"Invalid","slug":"UPPER"}')$q$,'23514',null,'PostgreSQL slug validation retained');
select throws_ok($q$select public.save_project(pg_temp.id('bad'),null,'{"title":"Invalid","slug":"valid","created_at":"2000-01-01"}')$q$,'22023',null,'Caller cannot control system timestamps');
select throws_ok($q$select public.save_post(pg_temp.id('bad'),null,'{"title":"Invalid","slug":"valid","role":"owner"}')$q$,'22023',null,'Arbitrary payload authorization fields rejected');
select throws_ok($q$select public.save_project(pg_temp.id('bad'),null,'{"title":"Invalid","slug":"valid"}','{"admin_profiles":[]}')$q$,'22023',null,'Unknown relation table rejected');
select lives_ok($q$select public.save_project(pg_temp.id('second'),null,'{"title":"Second","slug":"second-cms-fixture"}')$q$,'Second editorial resource created');
select throws_ok($q$select public.save_project(pg_temp.id('second'),(select updated_at from public.projects where id=pg_temp.id('second')),'{}',jsonb_build_object('features',jsonb_build_array(jsonb_build_object('id',pg_temp.id('feature'),'title','Stolen'))))$q$,'42501',null,'Child UUID cannot be reassigned across parents');
create temp table revision as select updated_at from public.projects where id=pg_temp.id('project');
update public.project_features set title='Direct REST equivalent' where id=pg_temp.id('feature');
select ok((select p.updated_at>r.updated_at from public.projects p cross join revision r where p.id=pg_temp.id('project')),'Direct relation edits advance parent revision');
select lives_ok($q$select public.save_project(pg_temp.id('project'),(select updated_at from public.projects where id=pg_temp.id('project')),'{"title":"Updated"}','{"features":[]}')$q$,'Correct revision can unlink children');
select is((select count(*) from public.project_features where project_id=pg_temp.id('project')),0::bigint,'Explicit unlink persisted');
select lives_ok($q$select public.save_post(pg_temp.id('post'),null,'{"title":"Post fixture","slug":"post-cms-fixture","content_markdown":"# Safe text"}')$q$,'Post transaction creates draft');
select throws_ok($q$select public.save_post(pg_temp.id('post'),(select updated_at from public.posts where id=pg_temp.id('post')),'{"status":"invalid"}')$q$,'23514',null,'Invalid post state denied');
select throws_ok($q$select public.save_post(pg_temp.id('post'),(select updated_at from public.posts where id=pg_temp.id('post')),'{"status":"published"}')$q$,'23514',null,'Publication requires timestamp');
select lives_ok($q$select public.save_experience(pg_temp.id('experience'),null,'{"position":"Fixture","organization":"Test","start_date":"2026-01-01"}','{"highlights":[{"title":"A real field","description":"Optional"}]}')$q$,'Experience and highlight transaction uses approved columns');
select throws_ok($q$select public.save_experience(pg_temp.id('experience'),(select updated_at from public.experiences where id=pg_temp.id('experience')),'{"end_date":"2025-01-01"}')$q$,'23514',null,'Experience date integrity retained');
select throws_ok($q$select public.save_post(pg_temp.id('post'),(select updated_at from public.posts where id=pg_temp.id('post')),'{}',jsonb_build_object('tags',jsonb_build_array(jsonb_build_object('tag_id',pg_temp.id('missing-tag')))))$q$,'23503',null,'Nonexistent taxonomy is rejected by FK');
reset role;
select finish();
rollback;
