-- All identities, records and grants below are ephemeral local fixtures.
begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select ok(not has_schema_privilege('anon','public','CREATE') and not has_schema_privilege('authenticated','public','CREATE'),'Clients cannot create API functions or views');
create function pg_temp.fixture_id(label text) returns uuid language sql immutable as $$select md5('portfolio-f5-test-only:' || label)::uuid$$;
create function pg_temp.affected(statement text) returns bigint language plpgsql as $$
declare n bigint; begin execute statement; get diagnostics n=row_count; return n; end $$;
create function pg_temp.login(label text) returns void language plpgsql as $$
begin
  perform set_config('request.jwt.claim.sub', pg_temp.fixture_id(label)::text, true);
  perform set_config('request.jwt.claims', jsonb_build_object('sub',pg_temp.fixture_id(label),'role','authenticated','user_metadata',jsonb_build_object('role','owner','active',true,'is_admin',true))::text,true);
end $$;
insert into auth.users(id) values (pg_temp.fixture_id('owner')), (pg_temp.fixture_id('inactive')), (pg_temp.fixture_id('normal'));
insert into public.admin_profiles(id,display_name,active) values
  (pg_temp.fixture_id('owner'),'Fixture owner',true), (pg_temp.fixture_id('inactive'),'Fixture inactive',false);
\ir fixtures/content.psql
create temp table expected_snapshot as select public.get_public_snapshot()-'generated_at' as value;
grant select on expected_snapshot to anon,authenticated;
select ok((select prosecdef from pg_proc where oid='private.is_portfolio_admin()'::regprocedure),'Owner lookup uses definer to avoid recursive RLS');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and p.oid is distinct from to_regprocedure('public.rls_auto_enable()')),3::bigint,'Exactly three audited application definers');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and p.oid is distinct from to_regprocedure('public.rls_auto_enable()') and (p.proconfig is null or not ('search_path=""'=any(p.proconfig)))),'Every application definer fixes empty search_path');
select ok(not exists(select 1 from pg_proc p where p.oid=to_regprocedure('public.rls_auto_enable()') and (p.prorettype<>'event_trigger'::regtype or not p.prosecdef or pg_get_userbyid(p.proowner)<>'postgres' or p.proconfig is distinct from array['search_path=pg_catalog'])), 'Optional platform Automatic RLS function has audited event-trigger type, owner and search_path');
select ok(not (select prosecdef from pg_proc where oid='public.get_public_snapshot()'::regprocedure),'Public snapshot remains invoker');
select ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v' and not ('security_invoker=true'=any(c.reloptions))),'All API views are invoker');
reset role;
select set_config('request.jwt.claim.sub','',true);
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is((select count(*) from public.projects where id=pg_temp.fixture_id('private-project')),0::bigint,'anon: direct draft UUID hidden');
select is((select count(*) from public.project_features where project_id=pg_temp.fixture_id('private-project')),0::bigint,'anon: child of draft UUID hidden');
select is((select count(*) from public.posts where status<>'published' or published_at>now()),0::bigint,'anon: draft/future posts hidden');
select is((select count(*) from public.technologies where not visible),0::bigint,'anon: hidden technologies denied');
select is(public.get_public_snapshot()-'generated_at',(select value from expected_snapshot),'anon: exact public snapshot');
select is((select email from public.public_contact_settings),null::text,'anon: hidden email redacted by view');
select is((select count(*) from public.public_media_assets where id=pg_temp.fixture_id('private-image')),0::bigint,'anon: private media hidden by view');
select throws_ok($attack$insert into public.projects(title,slug,published,published_at) values ('Attack','attack-anon',true,now())$attack$,'42501',null,'anon: published INSERT denied');
select throws_ok($attack$insert into public.admin_profiles(id,display_name,role,active) values (pg_temp.fixture_id('normal'),'Attack','owner',true)$attack$,'42501',null,'anon: cannot create owner');
select throws_ok($attack$update public.admin_profiles set active=true where id=pg_temp.fixture_id('inactive')$attack$,'42501',null,'anon: cannot change active');
select throws_ok($attack$update public.admin_profiles set role='owner'$attack$,'42501',null,'anon: cannot change role');
select throws_ok($attack$update public.admin_profiles set id=pg_temp.fixture_id('normal')$attack$,'42501',null,'anon: cannot replace identity UUID');
select throws_ok($attack$select private.set_updated_at()$attack$,'42501',null,'anon: cannot call private trigger helper');
select throws_ok($attack$select private.refresh_media_visibility()$attack$,'42501',null,'anon: cannot call operational helper');
select throws_ok($attack$select * from private.rate_limit_buckets$attack$,'42501',null,'anon: operational counters denied');
select throws_ok($attack$update public.site_settings set id=id$attack$,'42501',null,'anon: site_settings UPDATE denied');
select throws_ok($attack$delete from public.site_settings$attack$,'42501',null,'anon: site_settings DELETE denied');
select throws_ok($attack$update public.social_links set id=id$attack$,'42501',null,'anon: social_links UPDATE denied');
select throws_ok($attack$delete from public.social_links$attack$,'42501',null,'anon: social_links DELETE denied');
select throws_ok($attack$update public.projects set id=id$attack$,'42501',null,'anon: projects UPDATE denied');
select throws_ok($attack$delete from public.projects$attack$,'42501',null,'anon: projects DELETE denied');
select throws_ok($attack$update public.posts set id=id$attack$,'42501',null,'anon: posts UPDATE denied');
select throws_ok($attack$delete from public.posts$attack$,'42501',null,'anon: posts DELETE denied');
select throws_ok($attack$update public.technologies set id=id$attack$,'42501',null,'anon: technologies UPDATE denied');
select throws_ok($attack$delete from public.technologies$attack$,'42501',null,'anon: technologies DELETE denied');
select throws_ok($attack$update public.post_categories set id=id$attack$,'42501',null,'anon: post_categories UPDATE denied');
select throws_ok($attack$delete from public.post_categories$attack$,'42501',null,'anon: post_categories DELETE denied');
select throws_ok($attack$update public.experiences set id=id$attack$,'42501',null,'anon: experiences UPDATE denied');
select throws_ok($attack$delete from public.experiences$attack$,'42501',null,'anon: experiences DELETE denied');
select throws_ok($attack$update public.specialties set id=id$attack$,'42501',null,'anon: specialties UPDATE denied');
select throws_ok($attack$delete from public.specialties$attack$,'42501',null,'anon: specialties DELETE denied');
select throws_ok($attack$update public.work_principles set id=id$attack$,'42501',null,'anon: work_principles UPDATE denied');
select throws_ok($attack$delete from public.work_principles$attack$,'42501',null,'anon: work_principles DELETE denied');
select throws_ok($attack$update public.impact_metrics set id=id$attack$,'42501',null,'anon: impact_metrics UPDATE denied');
select throws_ok($attack$delete from public.impact_metrics$attack$,'42501',null,'anon: impact_metrics DELETE denied');
select throws_ok($attack$update public.project_features set id=id$attack$,'42501',null,'anon: project_features UPDATE denied');
select throws_ok($attack$delete from public.project_features$attack$,'42501',null,'anon: project_features DELETE denied');
select throws_ok($attack$update public.project_challenges set id=id$attack$,'42501',null,'anon: project_challenges UPDATE denied');
select throws_ok($attack$delete from public.project_challenges$attack$,'42501',null,'anon: project_challenges DELETE denied');
select throws_ok($attack$update public.project_metrics set id=id$attack$,'42501',null,'anon: project_metrics UPDATE denied');
select throws_ok($attack$delete from public.project_metrics$attack$,'42501',null,'anon: project_metrics DELETE denied');
select throws_ok($attack$update public.project_images set id=id$attack$,'42501',null,'anon: project_images UPDATE denied');
select throws_ok($attack$delete from public.project_images$attack$,'42501',null,'anon: project_images DELETE denied');
select throws_ok($attack$update public.project_technologies set sort_order=sort_order$attack$,'42501',null,'anon: project_technologies UPDATE denied');
select throws_ok($attack$delete from public.project_technologies$attack$,'42501',null,'anon: project_technologies DELETE denied');
select throws_ok($attack$update public.post_tags set tag_id=tag_id$attack$,'42501',null,'anon: post_tags UPDATE denied');
select throws_ok($attack$delete from public.post_tags$attack$,'42501',null,'anon: post_tags DELETE denied');
select throws_ok($attack$update public.post_category_relations set category_id=category_id$attack$,'42501',null,'anon: post_category_relations UPDATE denied');
select throws_ok($attack$delete from public.post_category_relations$attack$,'42501',null,'anon: post_category_relations DELETE denied');
select throws_ok($attack$update public.tags set id=id$attack$,'42501',null,'anon: tags UPDATE denied');
select throws_ok($attack$delete from public.tags$attack$,'42501',null,'anon: tags DELETE denied');
select throws_ok($attack$update public.experience_highlights set id=id$attack$,'42501',null,'anon: experience_highlights UPDATE denied');
select throws_ok($attack$delete from public.experience_highlights$attack$,'42501',null,'anon: experience_highlights DELETE denied');
select throws_ok($attack$update public.experience_projects set project_id=project_id$attack$,'42501',null,'anon: experience_projects UPDATE denied');
select throws_ok($attack$delete from public.experience_projects$attack$,'42501',null,'anon: experience_projects DELETE denied');
select throws_ok($attack$update public.experience_technologies set technology_id=technology_id$attack$,'42501',null,'anon: experience_technologies UPDATE denied');
select throws_ok($attack$delete from public.experience_technologies$attack$,'42501',null,'anon: experience_technologies DELETE denied');
select throws_ok($attack$update public.documents set id=id$attack$,'42501',null,'anon: documents UPDATE denied');
select throws_ok($attack$delete from public.documents$attack$,'42501',null,'anon: documents DELETE denied');
select throws_ok($attack$update public.media_references set id=id$attack$,'42501',null,'anon: media_references UPDATE denied');
select throws_ok($attack$delete from public.media_references$attack$,'42501',null,'anon: media_references DELETE denied');
select throws_ok($attack$update public.contact_settings set id=id$attack$,'42501',null,'anon: contact_settings UPDATE denied');
select throws_ok($attack$delete from public.contact_settings$attack$,'42501',null,'anon: contact_settings DELETE denied');
select throws_ok($attack$update public.media_assets set caption=caption$attack$,'42501',null,'anon: media_assets UPDATE denied');
select throws_ok($attack$delete from public.media_assets$attack$,'42501',null,'anon: media_assets DELETE denied');
select throws_ok($attack$select * from public.contact_messages$attack$,'42501',null,'anon: private contact_messages denied');
select throws_ok($attack$select * from public.analytics_events$attack$,'42501',null,'anon: private analytics_events denied');
select throws_ok($attack$select * from public.analytics_daily$attack$,'42501',null,'anon: private analytics_daily denied');
select throws_ok($attack$select * from public.analytics_daily_content$attack$,'42501',null,'anon: private analytics_daily_content denied');
select throws_ok($attack$select * from public.site_builds$attack$,'42501',null,'anon: private site_builds denied');
select throws_ok($attack$select * from public.admin_activity$attack$,'42501',null,'anon: private admin_activity denied');
select throws_ok($attack$select * from public.admin_profiles$attack$,'42501',null,'anon: private admin_profiles denied');
select throws_ok($attack$select * from public.contact_settings$attack$,'42501',null,'anon: private contact_settings denied');
select throws_ok($attack$select * from public.media_assets$attack$,'42501',null,'anon: private media_assets denied');
reset role;
select pg_temp.login('normal');
set local role authenticated;
select ok(not private.is_portfolio_admin(),'normal: client metadata does not authorize');
select is((select count(*) from public.projects where id=pg_temp.fixture_id('private-project')),0::bigint,'normal: direct draft UUID hidden');
select is((select count(*) from public.project_features where project_id=pg_temp.fixture_id('private-project')),0::bigint,'normal: child of draft UUID hidden');
select is((select count(*) from public.posts where status<>'published' or published_at>now()),0::bigint,'normal: draft/future posts hidden');
select is((select count(*) from public.technologies where not visible),0::bigint,'normal: hidden technologies denied');
select is(public.get_public_snapshot()-'generated_at',(select value from expected_snapshot),'normal: exact public snapshot');
select is((select email from public.public_contact_settings),null::text,'normal: hidden email redacted by view');
select is((select count(*) from public.public_media_assets where id=pg_temp.fixture_id('private-image')),0::bigint,'normal: private media hidden by view');
select throws_ok($attack$insert into public.projects(title,slug,published,published_at) values ('Attack','attack-normal',true,now())$attack$,'42501',null,'normal: published INSERT denied');
select throws_ok($attack$insert into public.admin_profiles(id,display_name,role,active) values (pg_temp.fixture_id('normal'),'Attack','owner',true)$attack$,'42501',null,'normal: cannot create owner');
select throws_ok($attack$update public.admin_profiles set active=true where id=pg_temp.fixture_id('inactive')$attack$,'42501',null,'normal: cannot change active');
select throws_ok($attack$update public.admin_profiles set role='owner'$attack$,'42501',null,'normal: cannot change role');
select throws_ok($attack$update public.admin_profiles set id=pg_temp.fixture_id('normal')$attack$,'42501',null,'normal: cannot replace identity UUID');
select throws_ok($attack$select private.set_updated_at()$attack$,'42501',null,'normal: cannot call private trigger helper');
select throws_ok($attack$select private.refresh_media_visibility()$attack$,'42501',null,'normal: cannot call operational helper');
select throws_ok($attack$select * from private.rate_limit_buckets$attack$,'42501',null,'normal: operational counters denied');
select is(pg_temp.affected('update public.site_settings set id=id'),0::bigint,'normal: site_settings UPDATE affects zero');
select is(pg_temp.affected('delete from public.site_settings'),0::bigint,'normal: site_settings DELETE affects zero');
select is(pg_temp.affected('update public.social_links set id=id'),0::bigint,'normal: social_links UPDATE affects zero');
select is(pg_temp.affected('delete from public.social_links'),0::bigint,'normal: social_links DELETE affects zero');
select is(pg_temp.affected('update public.projects set id=id'),0::bigint,'normal: projects UPDATE affects zero');
select is(pg_temp.affected('delete from public.projects'),0::bigint,'normal: projects DELETE affects zero');
select is(pg_temp.affected('update public.posts set id=id'),0::bigint,'normal: posts UPDATE affects zero');
select is(pg_temp.affected('delete from public.posts'),0::bigint,'normal: posts DELETE affects zero');
select is(pg_temp.affected('update public.technologies set id=id'),0::bigint,'normal: technologies UPDATE affects zero');
select is(pg_temp.affected('delete from public.technologies'),0::bigint,'normal: technologies DELETE affects zero');
select is(pg_temp.affected('update public.post_categories set id=id'),0::bigint,'normal: post_categories UPDATE affects zero');
select is(pg_temp.affected('delete from public.post_categories'),0::bigint,'normal: post_categories DELETE affects zero');
select is(pg_temp.affected('update public.experiences set id=id'),0::bigint,'normal: experiences UPDATE affects zero');
select is(pg_temp.affected('delete from public.experiences'),0::bigint,'normal: experiences DELETE affects zero');
select is(pg_temp.affected('update public.specialties set id=id'),0::bigint,'normal: specialties UPDATE affects zero');
select is(pg_temp.affected('delete from public.specialties'),0::bigint,'normal: specialties DELETE affects zero');
select is(pg_temp.affected('update public.work_principles set id=id'),0::bigint,'normal: work_principles UPDATE affects zero');
select is(pg_temp.affected('delete from public.work_principles'),0::bigint,'normal: work_principles DELETE affects zero');
select is(pg_temp.affected('update public.impact_metrics set id=id'),0::bigint,'normal: impact_metrics UPDATE affects zero');
select is(pg_temp.affected('delete from public.impact_metrics'),0::bigint,'normal: impact_metrics DELETE affects zero');
select is(pg_temp.affected('update public.project_features set id=id'),0::bigint,'normal: project_features UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_features'),0::bigint,'normal: project_features DELETE affects zero');
select is(pg_temp.affected('update public.project_challenges set id=id'),0::bigint,'normal: project_challenges UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_challenges'),0::bigint,'normal: project_challenges DELETE affects zero');
select is(pg_temp.affected('update public.project_metrics set id=id'),0::bigint,'normal: project_metrics UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_metrics'),0::bigint,'normal: project_metrics DELETE affects zero');
select is(pg_temp.affected('update public.project_images set id=id'),0::bigint,'normal: project_images UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_images'),0::bigint,'normal: project_images DELETE affects zero');
select is(pg_temp.affected('update public.project_technologies set sort_order=sort_order'),0::bigint,'normal: project_technologies UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_technologies'),0::bigint,'normal: project_technologies DELETE affects zero');
select is(pg_temp.affected('update public.post_tags set tag_id=tag_id'),0::bigint,'normal: post_tags UPDATE affects zero');
select is(pg_temp.affected('delete from public.post_tags'),0::bigint,'normal: post_tags DELETE affects zero');
select is(pg_temp.affected('update public.post_category_relations set category_id=category_id'),0::bigint,'normal: post_category_relations UPDATE affects zero');
select is(pg_temp.affected('delete from public.post_category_relations'),0::bigint,'normal: post_category_relations DELETE affects zero');
select is(pg_temp.affected('update public.tags set id=id'),0::bigint,'normal: tags UPDATE affects zero');
select is(pg_temp.affected('delete from public.tags'),0::bigint,'normal: tags DELETE affects zero');
select is(pg_temp.affected('update public.experience_highlights set id=id'),0::bigint,'normal: experience_highlights UPDATE affects zero');
select is(pg_temp.affected('delete from public.experience_highlights'),0::bigint,'normal: experience_highlights DELETE affects zero');
select is(pg_temp.affected('update public.experience_projects set project_id=project_id'),0::bigint,'normal: experience_projects UPDATE affects zero');
select is(pg_temp.affected('delete from public.experience_projects'),0::bigint,'normal: experience_projects DELETE affects zero');
select is(pg_temp.affected('update public.experience_technologies set technology_id=technology_id'),0::bigint,'normal: experience_technologies UPDATE affects zero');
select is(pg_temp.affected('delete from public.experience_technologies'),0::bigint,'normal: experience_technologies DELETE affects zero');
select is(pg_temp.affected('update public.documents set id=id'),0::bigint,'normal: documents UPDATE affects zero');
select is(pg_temp.affected('delete from public.documents'),0::bigint,'normal: documents DELETE affects zero');
select is(pg_temp.affected('update public.media_references set id=id'),0::bigint,'normal: media_references UPDATE affects zero');
select is(pg_temp.affected('delete from public.media_references'),0::bigint,'normal: media_references DELETE affects zero');
select is(pg_temp.affected('update public.contact_settings set id=id'),0::bigint,'normal: contact_settings UPDATE affects zero');
select is(pg_temp.affected('delete from public.contact_settings'),0::bigint,'normal: contact_settings DELETE affects zero');
select is(pg_temp.affected('update public.media_assets set caption=caption'),0::bigint,'normal: media_assets UPDATE affects zero');
select is(pg_temp.affected('delete from public.media_assets'),0::bigint,'normal: media_assets DELETE affects zero');
select is((select count(*) from public.contact_messages),0::bigint,'normal: private contact_messages rows hidden');
select is((select count(*) from public.analytics_events),0::bigint,'normal: private analytics_events rows hidden');
select is((select count(*) from public.analytics_daily),0::bigint,'normal: private analytics_daily rows hidden');
select is((select count(*) from public.analytics_daily_content),0::bigint,'normal: private analytics_daily_content rows hidden');
select is((select count(*) from public.site_builds),0::bigint,'normal: private site_builds rows hidden');
select is((select count(*) from public.admin_activity),0::bigint,'normal: private admin_activity rows hidden');
select is((select count(*) from public.admin_profiles),0::bigint,'normal: private admin_profiles rows hidden');
select is((select count(*) from public.contact_settings),0::bigint,'normal: private contact_settings rows hidden');
select is((select count(*) from public.media_assets),0::bigint,'normal: private media_assets rows hidden');
select is((select count(*) from public.admin_analytics_daily_dimensions),0::bigint,'normal: admin aggregate view hidden');
select is(pg_temp.affected('update public.project_features set project_id=''00000000-0000-0000-0000-000000000000'''),0::bigint,'normal: changing parent FK cannot bypass RLS');
reset role;
select pg_temp.login('inactive');
set local role authenticated;
select ok(not private.is_portfolio_admin(),'inactive: client metadata does not authorize');
select is((select count(*) from public.projects where id=pg_temp.fixture_id('private-project')),0::bigint,'inactive: direct draft UUID hidden');
select is((select count(*) from public.project_features where project_id=pg_temp.fixture_id('private-project')),0::bigint,'inactive: child of draft UUID hidden');
select is((select count(*) from public.posts where status<>'published' or published_at>now()),0::bigint,'inactive: draft/future posts hidden');
select is((select count(*) from public.technologies where not visible),0::bigint,'inactive: hidden technologies denied');
select is(public.get_public_snapshot()-'generated_at',(select value from expected_snapshot),'inactive: exact public snapshot');
select is((select email from public.public_contact_settings),null::text,'inactive: hidden email redacted by view');
select is((select count(*) from public.public_media_assets where id=pg_temp.fixture_id('private-image')),0::bigint,'inactive: private media hidden by view');
select throws_ok($attack$insert into public.projects(title,slug,published,published_at) values ('Attack','attack-inactive',true,now())$attack$,'42501',null,'inactive: published INSERT denied');
select throws_ok($attack$insert into public.admin_profiles(id,display_name,role,active) values (pg_temp.fixture_id('inactive'),'Attack','owner',true)$attack$,'42501',null,'inactive: cannot create owner');
select throws_ok($attack$update public.admin_profiles set active=true where id=pg_temp.fixture_id('inactive')$attack$,'42501',null,'inactive: cannot change active');
select throws_ok($attack$update public.admin_profiles set role='owner'$attack$,'42501',null,'inactive: cannot change role');
select throws_ok($attack$update public.admin_profiles set id=pg_temp.fixture_id('normal')$attack$,'42501',null,'inactive: cannot replace identity UUID');
select throws_ok($attack$select private.set_updated_at()$attack$,'42501',null,'inactive: cannot call private trigger helper');
select throws_ok($attack$select private.refresh_media_visibility()$attack$,'42501',null,'inactive: cannot call operational helper');
select throws_ok($attack$select * from private.rate_limit_buckets$attack$,'42501',null,'inactive: operational counters denied');
select is(pg_temp.affected('update public.site_settings set id=id'),0::bigint,'inactive: site_settings UPDATE affects zero');
select is(pg_temp.affected('delete from public.site_settings'),0::bigint,'inactive: site_settings DELETE affects zero');
select is(pg_temp.affected('update public.social_links set id=id'),0::bigint,'inactive: social_links UPDATE affects zero');
select is(pg_temp.affected('delete from public.social_links'),0::bigint,'inactive: social_links DELETE affects zero');
select is(pg_temp.affected('update public.projects set id=id'),0::bigint,'inactive: projects UPDATE affects zero');
select is(pg_temp.affected('delete from public.projects'),0::bigint,'inactive: projects DELETE affects zero');
select is(pg_temp.affected('update public.posts set id=id'),0::bigint,'inactive: posts UPDATE affects zero');
select is(pg_temp.affected('delete from public.posts'),0::bigint,'inactive: posts DELETE affects zero');
select is(pg_temp.affected('update public.technologies set id=id'),0::bigint,'inactive: technologies UPDATE affects zero');
select is(pg_temp.affected('delete from public.technologies'),0::bigint,'inactive: technologies DELETE affects zero');
select is(pg_temp.affected('update public.post_categories set id=id'),0::bigint,'inactive: post_categories UPDATE affects zero');
select is(pg_temp.affected('delete from public.post_categories'),0::bigint,'inactive: post_categories DELETE affects zero');
select is(pg_temp.affected('update public.experiences set id=id'),0::bigint,'inactive: experiences UPDATE affects zero');
select is(pg_temp.affected('delete from public.experiences'),0::bigint,'inactive: experiences DELETE affects zero');
select is(pg_temp.affected('update public.specialties set id=id'),0::bigint,'inactive: specialties UPDATE affects zero');
select is(pg_temp.affected('delete from public.specialties'),0::bigint,'inactive: specialties DELETE affects zero');
select is(pg_temp.affected('update public.work_principles set id=id'),0::bigint,'inactive: work_principles UPDATE affects zero');
select is(pg_temp.affected('delete from public.work_principles'),0::bigint,'inactive: work_principles DELETE affects zero');
select is(pg_temp.affected('update public.impact_metrics set id=id'),0::bigint,'inactive: impact_metrics UPDATE affects zero');
select is(pg_temp.affected('delete from public.impact_metrics'),0::bigint,'inactive: impact_metrics DELETE affects zero');
select is(pg_temp.affected('update public.project_features set id=id'),0::bigint,'inactive: project_features UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_features'),0::bigint,'inactive: project_features DELETE affects zero');
select is(pg_temp.affected('update public.project_challenges set id=id'),0::bigint,'inactive: project_challenges UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_challenges'),0::bigint,'inactive: project_challenges DELETE affects zero');
select is(pg_temp.affected('update public.project_metrics set id=id'),0::bigint,'inactive: project_metrics UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_metrics'),0::bigint,'inactive: project_metrics DELETE affects zero');
select is(pg_temp.affected('update public.project_images set id=id'),0::bigint,'inactive: project_images UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_images'),0::bigint,'inactive: project_images DELETE affects zero');
select is(pg_temp.affected('update public.project_technologies set sort_order=sort_order'),0::bigint,'inactive: project_technologies UPDATE affects zero');
select is(pg_temp.affected('delete from public.project_technologies'),0::bigint,'inactive: project_technologies DELETE affects zero');
select is(pg_temp.affected('update public.post_tags set tag_id=tag_id'),0::bigint,'inactive: post_tags UPDATE affects zero');
select is(pg_temp.affected('delete from public.post_tags'),0::bigint,'inactive: post_tags DELETE affects zero');
select is(pg_temp.affected('update public.post_category_relations set category_id=category_id'),0::bigint,'inactive: post_category_relations UPDATE affects zero');
select is(pg_temp.affected('delete from public.post_category_relations'),0::bigint,'inactive: post_category_relations DELETE affects zero');
select is(pg_temp.affected('update public.tags set id=id'),0::bigint,'inactive: tags UPDATE affects zero');
select is(pg_temp.affected('delete from public.tags'),0::bigint,'inactive: tags DELETE affects zero');
select is(pg_temp.affected('update public.experience_highlights set id=id'),0::bigint,'inactive: experience_highlights UPDATE affects zero');
select is(pg_temp.affected('delete from public.experience_highlights'),0::bigint,'inactive: experience_highlights DELETE affects zero');
select is(pg_temp.affected('update public.experience_projects set project_id=project_id'),0::bigint,'inactive: experience_projects UPDATE affects zero');
select is(pg_temp.affected('delete from public.experience_projects'),0::bigint,'inactive: experience_projects DELETE affects zero');
select is(pg_temp.affected('update public.experience_technologies set technology_id=technology_id'),0::bigint,'inactive: experience_technologies UPDATE affects zero');
select is(pg_temp.affected('delete from public.experience_technologies'),0::bigint,'inactive: experience_technologies DELETE affects zero');
select is(pg_temp.affected('update public.documents set id=id'),0::bigint,'inactive: documents UPDATE affects zero');
select is(pg_temp.affected('delete from public.documents'),0::bigint,'inactive: documents DELETE affects zero');
select is(pg_temp.affected('update public.media_references set id=id'),0::bigint,'inactive: media_references UPDATE affects zero');
select is(pg_temp.affected('delete from public.media_references'),0::bigint,'inactive: media_references DELETE affects zero');
select is(pg_temp.affected('update public.contact_settings set id=id'),0::bigint,'inactive: contact_settings UPDATE affects zero');
select is(pg_temp.affected('delete from public.contact_settings'),0::bigint,'inactive: contact_settings DELETE affects zero');
select is(pg_temp.affected('update public.media_assets set caption=caption'),0::bigint,'inactive: media_assets UPDATE affects zero');
select is(pg_temp.affected('delete from public.media_assets'),0::bigint,'inactive: media_assets DELETE affects zero');
select is((select count(*) from public.contact_messages),0::bigint,'inactive: private contact_messages rows hidden');
select is((select count(*) from public.analytics_events),0::bigint,'inactive: private analytics_events rows hidden');
select is((select count(*) from public.analytics_daily),0::bigint,'inactive: private analytics_daily rows hidden');
select is((select count(*) from public.analytics_daily_content),0::bigint,'inactive: private analytics_daily_content rows hidden');
select is((select count(*) from public.site_builds),0::bigint,'inactive: private site_builds rows hidden');
select is((select count(*) from public.admin_activity),0::bigint,'inactive: private admin_activity rows hidden');
select is((select count(*) from public.admin_profiles),0::bigint,'inactive: private admin_profiles rows hidden');
select is((select count(*) from public.contact_settings),0::bigint,'inactive: private contact_settings rows hidden');
select is((select count(*) from public.media_assets),0::bigint,'inactive: private media_assets rows hidden');
select is((select count(*) from public.admin_analytics_daily_dimensions),0::bigint,'inactive: admin aggregate view hidden');
select is(pg_temp.affected('update public.project_features set project_id=''00000000-0000-0000-0000-000000000000'''),0::bigint,'inactive: changing parent FK cannot bypass RLS');
reset role;
select pg_temp.login('owner');
set local role authenticated;
select ok(private.is_portfolio_admin(),'Active owner recognized only through auth.uid and profile');
select is(public.get_public_snapshot()-'generated_at',(select value from expected_snapshot),'Owner public snapshot still excludes private data');
select is((select count(*) from public.projects),4::bigint,'Owner reads drafts and public content');
select lives_ok($operation$update public.admin_profiles set display_name='Updated fixture',avatar_url='https://example.com/avatar.png'$operation$,'Owner may edit own display fields');
select throws_ok($attack$update public.admin_profiles set active=false$attack$,'42501',null,'Owner cannot mutate authorization attributes or create second owner');
select throws_ok($attack$update public.admin_profiles set role='owner'$attack$,'42501',null,'Owner cannot mutate authorization attributes or create second owner');
select throws_ok($attack$update public.admin_profiles set id=gen_random_uuid()$attack$,'42501',null,'Owner cannot mutate authorization attributes or create second owner');
select throws_ok($attack$insert into public.admin_profiles(id,display_name,active) values (pg_temp.fixture_id('normal'),'Attack',true)$attack$,'42501',null,'Owner cannot mutate authorization attributes or create second owner');
select throws_ok($attack$delete from public.admin_profiles$attack$,'42501',null,'Owner cannot mutate authorization attributes or create second owner');
select is((select count(*) from public.contact_messages),1::bigint,'Owner may read contact_messages');
select is((select count(*) from public.analytics_events),1::bigint,'Owner may read analytics_events');
select is((select count(*) from public.site_builds),1::bigint,'Owner may read site_builds');
select is((select count(*) from public.admin_activity),1::bigint,'Owner may read admin_activity');
select lives_ok($operation$update public.contact_messages set status='read'$operation$,'Owner may update message status');
select throws_ok($attack$update public.contact_messages set message='Forged body'$attack$,'42501',null,'Owner cannot edit message body');
select throws_ok($attack$update public.contact_messages set notification_status='sent'$attack$,'42501',null,'Owner cannot impersonate notification service');
select throws_ok($attack$insert into public.analytics_events(event_id,session_hash,event_type,pathname) values(gen_random_uuid(),repeat('a',64),'page_view','/')$attack$,'42501',null,'Operational writes are not browser privileges');
select throws_ok($attack$update public.site_builds set status='failed'$attack$,'42501',null,'Operational writes are not browser privileges');
select throws_ok($attack$delete from public.admin_activity$attack$,'42501',null,'Operational writes are not browser privileges');
select throws_ok($attack$insert into public.admin_activity(action,entity_type) values('fake','project')$attack$,'42501',null,'Operational writes are not browser privileges');
select lives_ok($operation$insert into public.projects(id,title,slug) values(pg_temp.fixture_id('crud-project'),'CRUD','crud-project')$operation$,'Owner INSERT projects');
select is(pg_temp.affected($stmt$update public.projects set title=title where id=pg_temp.fixture_id('crud-project')$stmt$),1::bigint,'Owner UPDATE projects');
select is(pg_temp.affected($stmt$delete from public.projects where id=pg_temp.fixture_id('crud-project')$stmt$),1::bigint,'Owner DELETE projects');
select lives_ok($operation$insert into public.posts(id,title,slug) values(pg_temp.fixture_id('crud-post'),'CRUD','crud-post')$operation$,'Owner INSERT posts');
select is(pg_temp.affected($stmt$update public.posts set title=title where id=pg_temp.fixture_id('crud-post')$stmt$),1::bigint,'Owner UPDATE posts');
select is(pg_temp.affected($stmt$delete from public.posts where id=pg_temp.fixture_id('crud-post')$stmt$),1::bigint,'Owner DELETE posts');
select lives_ok($operation$insert into public.technologies(id,name,slug,category) values(pg_temp.fixture_id('crud-technology'),'CRUD','crud-technology','test')$operation$,'Owner INSERT technologies');
select is(pg_temp.affected($stmt$update public.technologies set name=name where id=pg_temp.fixture_id('crud-technology')$stmt$),1::bigint,'Owner UPDATE technologies');
select is(pg_temp.affected($stmt$delete from public.technologies where id=pg_temp.fixture_id('crud-technology')$stmt$),1::bigint,'Owner DELETE technologies');
select lives_ok($operation$insert into public.post_categories(id,name,slug) values(pg_temp.fixture_id('crud-category'),'CRUD','crud-category')$operation$,'Owner INSERT post_categories');
select is(pg_temp.affected($stmt$update public.post_categories set name=name where id=pg_temp.fixture_id('crud-category')$stmt$),1::bigint,'Owner UPDATE post_categories');
select is(pg_temp.affected($stmt$delete from public.post_categories where id=pg_temp.fixture_id('crud-category')$stmt$),1::bigint,'Owner DELETE post_categories');
select lives_ok($operation$insert into public.tags(id,name,slug) values(pg_temp.fixture_id('crud-tag'),'CRUD','crud-tag')$operation$,'Owner INSERT tags');
select is(pg_temp.affected($stmt$update public.tags set name=name where id=pg_temp.fixture_id('crud-tag')$stmt$),1::bigint,'Owner UPDATE tags');
select is(pg_temp.affected($stmt$delete from public.tags where id=pg_temp.fixture_id('crud-tag')$stmt$),1::bigint,'Owner DELETE tags');
select lives_ok($operation$insert into public.experiences(id,position,organization,start_date) values(pg_temp.fixture_id('crud-experience'),'CRUD','Test','2020-01-01')$operation$,'Owner INSERT experiences');
select is(pg_temp.affected($stmt$update public.experiences set position=position where id=pg_temp.fixture_id('crud-experience')$stmt$),1::bigint,'Owner UPDATE experiences');
select is(pg_temp.affected($stmt$delete from public.experiences where id=pg_temp.fixture_id('crud-experience')$stmt$),1::bigint,'Owner DELETE experiences');
select lives_ok($operation$insert into public.specialties(id,title,slug) values(pg_temp.fixture_id('crud-specialty'),'CRUD','crud-specialty')$operation$,'Owner INSERT specialties');
select is(pg_temp.affected($stmt$update public.specialties set title=title where id=pg_temp.fixture_id('crud-specialty')$stmt$),1::bigint,'Owner UPDATE specialties');
select is(pg_temp.affected($stmt$delete from public.specialties where id=pg_temp.fixture_id('crud-specialty')$stmt$),1::bigint,'Owner DELETE specialties');
select lives_ok($operation$insert into public.work_principles(id,number,title) values(pg_temp.fixture_id('crud-principle'),99,'CRUD')$operation$,'Owner INSERT work_principles');
select is(pg_temp.affected($stmt$update public.work_principles set title=title where id=pg_temp.fixture_id('crud-principle')$stmt$),1::bigint,'Owner UPDATE work_principles');
select is(pg_temp.affected($stmt$delete from public.work_principles where id=pg_temp.fixture_id('crud-principle')$stmt$),1::bigint,'Owner DELETE work_principles');
select lives_ok($operation$insert into public.impact_metrics(id,value,label) values(pg_temp.fixture_id('crud-impact'),'test','CRUD')$operation$,'Owner INSERT impact_metrics');
select is(pg_temp.affected($stmt$update public.impact_metrics set label=label where id=pg_temp.fixture_id('crud-impact')$stmt$),1::bigint,'Owner UPDATE impact_metrics');
select is(pg_temp.affected($stmt$delete from public.impact_metrics where id=pg_temp.fixture_id('crud-impact')$stmt$),1::bigint,'Owner DELETE impact_metrics');
select lives_ok($operation$insert into public.social_links(id,platform,label,url) values(pg_temp.fixture_id('crud-social'),'test','CRUD','https://example.com')$operation$,'Owner INSERT social_links');
select is(pg_temp.affected($stmt$update public.social_links set label=label where id=pg_temp.fixture_id('crud-social')$stmt$),1::bigint,'Owner UPDATE social_links');
select is(pg_temp.affected($stmt$delete from public.social_links where id=pg_temp.fixture_id('crud-social')$stmt$),1::bigint,'Owner DELETE social_links');
select lives_ok($operation$insert into public.project_features(id,project_id,title) values(pg_temp.fixture_id('crud-feature'),pg_temp.fixture_id('project'),'CRUD')$operation$,'Owner INSERT project_features');
select is(pg_temp.affected($stmt$update public.project_features set title=title where id=pg_temp.fixture_id('crud-feature')$stmt$),1::bigint,'Owner UPDATE project_features');
select is(pg_temp.affected($stmt$delete from public.project_features where id=pg_temp.fixture_id('crud-feature')$stmt$),1::bigint,'Owner DELETE project_features');
select lives_ok($operation$insert into public.project_images(id,project_id,asset_id,alt_text) values(pg_temp.fixture_id('crud-image'),pg_temp.fixture_id('project'),pg_temp.fixture_id('image'),'CRUD')$operation$,'Owner INSERT project_images');
select is(pg_temp.affected($stmt$update public.project_images set alt_text=alt_text where id=pg_temp.fixture_id('crud-image')$stmt$),1::bigint,'Owner UPDATE project_images');
select is(pg_temp.affected($stmt$delete from public.project_images where id=pg_temp.fixture_id('crud-image')$stmt$),1::bigint,'Owner DELETE project_images');
select lives_ok($operation$insert into public.project_metrics(id,project_id,value,label) values(pg_temp.fixture_id('crud-metric'),pg_temp.fixture_id('project'),'test','CRUD')$operation$,'Owner INSERT project_metrics');
select is(pg_temp.affected($stmt$update public.project_metrics set label=label where id=pg_temp.fixture_id('crud-metric')$stmt$),1::bigint,'Owner UPDATE project_metrics');
select is(pg_temp.affected($stmt$delete from public.project_metrics where id=pg_temp.fixture_id('crud-metric')$stmt$),1::bigint,'Owner DELETE project_metrics');
select lives_ok($operation$insert into public.project_challenges(id,project_id,title) values(pg_temp.fixture_id('crud-challenge'),pg_temp.fixture_id('project'),'CRUD')$operation$,'Owner INSERT project_challenges');
select is(pg_temp.affected($stmt$update public.project_challenges set title=title where id=pg_temp.fixture_id('crud-challenge')$stmt$),1::bigint,'Owner UPDATE project_challenges');
select is(pg_temp.affected($stmt$delete from public.project_challenges where id=pg_temp.fixture_id('crud-challenge')$stmt$),1::bigint,'Owner DELETE project_challenges');
select lives_ok($operation$insert into public.experience_highlights(id,experience_id,title) values(pg_temp.fixture_id('crud-highlight'),pg_temp.fixture_id('experience'),'CRUD')$operation$,'Owner INSERT experience_highlights');
select is(pg_temp.affected($stmt$update public.experience_highlights set title=title where id=pg_temp.fixture_id('crud-highlight')$stmt$),1::bigint,'Owner UPDATE experience_highlights');
select is(pg_temp.affected($stmt$delete from public.experience_highlights where id=pg_temp.fixture_id('crud-highlight')$stmt$),1::bigint,'Owner DELETE experience_highlights');
select lives_ok($operation$insert into public.documents(id,title,asset_id) values(pg_temp.fixture_id('crud-document'),'CRUD',pg_temp.fixture_id('pdf'))$operation$,'Owner INSERT documents');
select is(pg_temp.affected($stmt$update public.documents set title=title where id=pg_temp.fixture_id('crud-document')$stmt$),1::bigint,'Owner UPDATE documents');
select is(pg_temp.affected($stmt$delete from public.documents where id=pg_temp.fixture_id('crud-document')$stmt$),1::bigint,'Owner DELETE documents');
select lives_ok($operation$insert into storage.objects(bucket_id,name,owner_id) values('private','temporary/10000000-0000-4000-8000-000000000006.png',pg_temp.fixture_id('owner')::text)$operation$,'Owner allocates object before metadata');
select lives_ok($operation$insert into public.media_assets(id,storage_bucket,storage_path,public_url,filename,mime_type,file_size,width,height,alt_text) values(pg_temp.fixture_id('crud-asset'),'private','temporary/10000000-0000-4000-8000-000000000006.png',null,'crud.png','image/png',12,1,1,'Fixture')$operation$,'Owner INSERT media_assets');
select is(pg_temp.affected($stmt$update public.media_assets set caption=caption where id=pg_temp.fixture_id('crud-asset')$stmt$),1::bigint,'Owner UPDATE media_assets');
select is(pg_temp.affected($stmt$delete from public.media_assets where id=pg_temp.fixture_id('crud-asset')$stmt$),1::bigint,'Owner DELETE media_assets');
select lives_ok($operation$insert into public.media_references(id,asset_id,post_id,field) values(pg_temp.fixture_id('crud-ref'),pg_temp.fixture_id('image'),pg_temp.fixture_id('post'),'excerpt')$operation$,'Owner INSERT media_references');
select is(pg_temp.affected($stmt$update public.media_references set field=field where id=pg_temp.fixture_id('crud-ref')$stmt$),1::bigint,'Owner UPDATE media_references');
select is(pg_temp.affected($stmt$delete from public.media_references where id=pg_temp.fixture_id('crud-ref')$stmt$),1::bigint,'Owner DELETE media_references');
select lives_ok($operation$insert into public.project_technologies(project_id,technology_id) values(pg_temp.fixture_id('future-project'),pg_temp.fixture_id('technology'))$operation$,'Owner INSERT project_technologies');
select is(pg_temp.affected($stmt$update public.project_technologies set sort_order=sort_order where project_id=pg_temp.fixture_id('future-project')$stmt$),1::bigint,'Owner UPDATE project_technologies');
select is(pg_temp.affected($stmt$delete from public.project_technologies where project_id=pg_temp.fixture_id('future-project')$stmt$),1::bigint,'Owner DELETE project_technologies');
select lives_ok($operation$insert into public.post_category_relations(post_id,category_id) values(pg_temp.fixture_id('future-post'),pg_temp.fixture_id('private-category'))$operation$,'Owner INSERT post_category_relations');
select is(pg_temp.affected($stmt$update public.post_category_relations set category_id=category_id where post_id=pg_temp.fixture_id('future-post')$stmt$),1::bigint,'Owner UPDATE post_category_relations');
select is(pg_temp.affected($stmt$delete from public.post_category_relations where post_id=pg_temp.fixture_id('future-post')$stmt$),1::bigint,'Owner DELETE post_category_relations');
select lives_ok($operation$insert into public.post_tags(post_id,tag_id) values(pg_temp.fixture_id('future-post'),pg_temp.fixture_id('tag'))$operation$,'Owner INSERT post_tags');
select is(pg_temp.affected($stmt$update public.post_tags set tag_id=tag_id where post_id=pg_temp.fixture_id('future-post')$stmt$),1::bigint,'Owner UPDATE post_tags');
select is(pg_temp.affected($stmt$delete from public.post_tags where post_id=pg_temp.fixture_id('future-post')$stmt$),1::bigint,'Owner DELETE post_tags');
select lives_ok($operation$insert into public.experience_projects(experience_id,project_id) values(pg_temp.fixture_id('experience'),pg_temp.fixture_id('future-project'))$operation$,'Owner INSERT experience_projects');
select is(pg_temp.affected($stmt$update public.experience_projects set project_id=project_id where experience_id=pg_temp.fixture_id('experience') and project_id=pg_temp.fixture_id('future-project')$stmt$),1::bigint,'Owner UPDATE experience_projects');
select is(pg_temp.affected($stmt$delete from public.experience_projects where experience_id=pg_temp.fixture_id('experience') and project_id=pg_temp.fixture_id('future-project')$stmt$),1::bigint,'Owner DELETE experience_projects');
select lives_ok($operation$insert into public.experience_technologies(experience_id,technology_id) values(pg_temp.fixture_id('private-experience'),pg_temp.fixture_id('private-technology'))$operation$,'Owner INSERT experience_technologies');
select is(pg_temp.affected($stmt$update public.experience_technologies set technology_id=technology_id where experience_id=pg_temp.fixture_id('private-experience')$stmt$),1::bigint,'Owner UPDATE experience_technologies');
select is(pg_temp.affected($stmt$delete from public.experience_technologies where experience_id=pg_temp.fixture_id('private-experience')$stmt$),1::bigint,'Owner DELETE experience_technologies');
select lives_ok($operation$delete from public.site_settings$operation$,'Owner DELETE singleton site_settings');
select lives_ok($operation$insert into public.site_settings(site_name,brand_short) values('Fixture','AL')$operation$,'Owner INSERT singleton site_settings');
select lives_ok($operation$update public.site_settings set singleton=true$operation$,'Owner UPDATE singleton site_settings');
select lives_ok($operation$delete from public.contact_settings$operation$,'Owner DELETE singleton contact_settings');
select lives_ok($operation$insert into public.contact_settings(singleton) values(true)$operation$,'Owner INSERT singleton contact_settings');
select lives_ok($operation$update public.contact_settings set singleton=true$operation$,'Owner UPDATE singleton contact_settings');
select throws_ok($attack$insert into public.media_assets(storage_bucket,storage_path,filename,mime_type,file_size,created_by) values('private','temporary/forged.png','forged.png','image/png',10,pg_temp.fixture_id('inactive'))$attack$,'42501',null,'WITH CHECK rejects forged asset author');
select throws_ok($attack$update public.media_assets set created_by=pg_temp.fixture_id('inactive')$attack$,'42501',null,'Owner cannot change asset attribution');
reset role;
-- Qualified owner lookup cannot be redirected through a caller-controlled search_path.
select pg_temp.login('normal');
create temporary table admin_profiles(id uuid,active boolean,role text);
insert into pg_temp.admin_profiles values(pg_temp.fixture_id('normal'),true,'owner');
grant select on pg_temp.admin_profiles to authenticated;
set local search_path=pg_temp,public,extensions;
set local role authenticated;
select ok(not private.is_portfolio_admin(),'Definer ignores a forged temp profile table');
select is((select count(*) from public.projects where not published),0::bigint,'search_path manipulation cannot expose drafts');
reset role;
select * from finish();
rollback;
