// Generated by npm run db:types from local PostgreSQL. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  private: {
    Tables: {
      analytics_daily_dimensions: {
        Row: {
          article_shares: number;
          contact_submits: number;
          cv_downloads: number;
          date: string;
          demo_clicks: number;
          dimension: string;
          email_clicks: number;
          email_copies: number;
          github_clicks: number;
          linkedin_clicks: number;
          page_views: number;
          post_views: number;
          project_views: number;
          unique_sessions: number;
          value: string;
          whatsapp_clicks: number;
        };
        Insert: {
          article_shares?: number;
          contact_submits?: number;
          cv_downloads?: number;
          date: string;
          demo_clicks?: number;
          dimension: string;
          email_clicks?: number;
          email_copies?: number;
          github_clicks?: number;
          linkedin_clicks?: number;
          page_views?: number;
          post_views?: number;
          project_views?: number;
          unique_sessions?: number;
          value: string;
          whatsapp_clicks?: number;
        };
        Update: {
          article_shares?: number;
          contact_submits?: number;
          cv_downloads?: number;
          date?: string;
          demo_clicks?: number;
          dimension?: string;
          email_clicks?: number;
          email_copies?: number;
          github_clicks?: number;
          linkedin_clicks?: number;
          page_views?: number;
          post_views?: number;
          project_views?: number;
          unique_sessions?: number;
          value?: string;
          whatsapp_clicks?: number;
        };
        Relationships: [];
      };
      analytics_daily_sessions: {
        Row: {
          content_id: string | null;
          content_type: string;
          date: string;
          id: string;
          session_hash: string;
        };
        Insert: {
          content_id?: string | null;
          content_type?: string;
          date: string;
          id?: string;
          session_hash: string;
        };
        Update: {
          content_id?: string | null;
          content_type?: string;
          date?: string;
          id?: string;
          session_hash?: string;
        };
        Relationships: [];
      };
      rate_limit_buckets: {
        Row: {
          action: string;
          expires_at: string;
          hits: number;
          key_hash: string;
          window_start: string;
        };
        Insert: {
          action: string;
          expires_at: string;
          hits?: number;
          key_hash: string;
          window_start: string;
        };
        Update: {
          action?: string;
          expires_at?: string;
          hits?: number;
          key_hash?: string;
          window_start?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      consume_edge_limit: {
        Args: {
          p_action: string;
          p_hash: string;
          p_limit: number;
          p_seconds: number;
        };
        Returns: boolean;
      };
      is_portfolio_admin: { Args: never; Returns: boolean };
      read_public_contact: {
        Args: never;
        Returns: {
          cta_description: string;
          cta_title: string;
          cv_enabled: boolean;
          email: string;
          email_visible: boolean;
          form_enabled: boolean;
          id: string;
          whatsapp_cta_label: string;
          whatsapp_default_message: string;
          whatsapp_number: string;
          whatsapp_visible: boolean;
        }[];
      };
      read_public_media: {
        Args: never;
        Returns: {
          alt_text: string;
          caption: string;
          category: string;
          decorative: boolean;
          file_size: number;
          filename: string;
          height: number;
          id: string;
          mime_type: string;
          public_url: string;
          visibility: string;
          width: number;
        }[];
      };
      storage_path_allowed: {
        Args: { bucket: string; object_name: string };
        Returns: boolean;
      };
      update_analytics_popularity: { Args: never; Returns: undefined };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      admin_activity: {
        Row: {
          action: string;
          admin_id: string | null;
          created_at: string;
          entity_id: string | null;
          entity_type: string;
          id: string;
          metadata: Json;
        };
        Insert: {
          action: string;
          admin_id?: string | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type: string;
          id?: string;
          metadata?: Json;
        };
        Update: {
          action?: string;
          admin_id?: string | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string;
          id?: string;
          metadata?: Json;
        };
        Relationships: [
          {
            foreignKeyName: 'admin_activity_admin_id_fkey';
            columns: ['admin_id'];
            isOneToOne: false;
            referencedRelation: 'admin_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      admin_profiles: {
        Row: {
          active: boolean;
          avatar_url: string | null;
          created_at: string;
          display_name: string;
          id: string;
          role: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          avatar_url?: string | null;
          created_at?: string;
          display_name: string;
          id: string;
          role?: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string;
          id?: string;
          role?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      analytics_daily: {
        Row: {
          article_shares: number;
          contact_submits: number;
          cv_downloads: number;
          date: string;
          demo_clicks: number;
          email_clicks: number;
          email_copies: number;
          github_clicks: number;
          linkedin_clicks: number;
          page_views: number;
          post_views: number;
          project_views: number;
          unique_sessions: number;
          whatsapp_clicks: number;
        };
        Insert: {
          article_shares?: number;
          contact_submits?: number;
          cv_downloads?: number;
          date: string;
          demo_clicks?: number;
          email_clicks?: number;
          email_copies?: number;
          github_clicks?: number;
          linkedin_clicks?: number;
          page_views?: number;
          post_views?: number;
          project_views?: number;
          unique_sessions?: number;
          whatsapp_clicks?: number;
        };
        Update: {
          article_shares?: number;
          contact_submits?: number;
          cv_downloads?: number;
          date?: string;
          demo_clicks?: number;
          email_clicks?: number;
          email_copies?: number;
          github_clicks?: number;
          linkedin_clicks?: number;
          page_views?: number;
          post_views?: number;
          project_views?: number;
          unique_sessions?: number;
          whatsapp_clicks?: number;
        };
        Relationships: [];
      };
      analytics_daily_content: {
        Row: {
          content_id: string;
          content_type: string;
          date: string;
          interactions: number;
          unique_sessions: number;
          views: number;
        };
        Insert: {
          content_id: string;
          content_type: string;
          date: string;
          interactions?: number;
          unique_sessions?: number;
          views?: number;
        };
        Update: {
          content_id?: string;
          content_type?: string;
          date?: string;
          interactions?: number;
          unique_sessions?: number;
          views?: number;
        };
        Relationships: [];
      };
      analytics_events: {
        Row: {
          browser_family: string | null;
          created_at: string;
          device_type: string | null;
          event_id: string;
          event_type: string;
          id: string;
          pathname: string;
          post_id: string | null;
          project_id: string | null;
          referrer_domain: string | null;
          session_hash: string;
        };
        Insert: {
          browser_family?: string | null;
          created_at?: string;
          device_type?: string | null;
          event_id: string;
          event_type: string;
          id?: string;
          pathname: string;
          post_id?: string | null;
          project_id?: string | null;
          referrer_domain?: string | null;
          session_hash: string;
        };
        Update: {
          browser_family?: string | null;
          created_at?: string;
          device_type?: string | null;
          event_id?: string;
          event_type?: string;
          id?: string;
          pathname?: string;
          post_id?: string | null;
          project_id?: string | null;
          referrer_domain?: string | null;
          session_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'analytics_events_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'analytics_events_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      contact_messages: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          message: string;
          name: string;
          notification_status: string;
          status: string;
          subject: string;
          submission_id: string;
          updated_at: string;
          user_agent_summary: string | null;
        };
        Insert: {
          created_at?: string;
          email: string;
          id?: string;
          message: string;
          name: string;
          notification_status?: string;
          status?: string;
          subject: string;
          submission_id: string;
          updated_at?: string;
          user_agent_summary?: string | null;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: string;
          message?: string;
          name?: string;
          notification_status?: string;
          status?: string;
          subject?: string;
          submission_id?: string;
          updated_at?: string;
          user_agent_summary?: string | null;
        };
        Relationships: [];
      };
      contact_settings: {
        Row: {
          created_at: string;
          cta_description: string | null;
          cta_title: string | null;
          cv_enabled: boolean;
          email: string | null;
          email_visible: boolean;
          form_enabled: boolean;
          id: string;
          singleton: boolean;
          updated_at: string;
          whatsapp_cta_label: string | null;
          whatsapp_default_message: string | null;
          whatsapp_number: string | null;
          whatsapp_visible: boolean;
        };
        Insert: {
          created_at?: string;
          cta_description?: string | null;
          cta_title?: string | null;
          cv_enabled?: boolean;
          email?: string | null;
          email_visible?: boolean;
          form_enabled?: boolean;
          id?: string;
          singleton?: boolean;
          updated_at?: string;
          whatsapp_cta_label?: string | null;
          whatsapp_default_message?: string | null;
          whatsapp_number?: string | null;
          whatsapp_visible?: boolean;
        };
        Update: {
          created_at?: string;
          cta_description?: string | null;
          cta_title?: string | null;
          cv_enabled?: boolean;
          email?: string | null;
          email_visible?: boolean;
          form_enabled?: boolean;
          id?: string;
          singleton?: boolean;
          updated_at?: string;
          whatsapp_cta_label?: string | null;
          whatsapp_default_message?: string | null;
          whatsapp_number?: string | null;
          whatsapp_visible?: boolean;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          active: boolean;
          asset_id: string;
          created_at: string;
          id: string;
          public_url: string | null;
          storage_path: string;
          title: string;
          type: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          asset_id: string;
          created_at?: string;
          id?: string;
          public_url?: string | null;
          storage_path: string;
          title: string;
          type?: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          asset_id?: string;
          created_at?: string;
          id?: string;
          public_url?: string | null;
          storage_path?: string;
          title?: string;
          type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'documents_asset_id_fkey';
            columns: ['asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
        ];
      };
      experience_highlights: {
        Row: {
          created_at: string;
          description: string | null;
          experience_id: string;
          id: string;
          sort_order: number;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          experience_id: string;
          id?: string;
          sort_order?: number;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          experience_id?: string;
          id?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'experience_highlights_experience_id_fkey';
            columns: ['experience_id'];
            isOneToOne: false;
            referencedRelation: 'experiences';
            referencedColumns: ['id'];
          },
        ];
      };
      experience_projects: {
        Row: {
          experience_id: string;
          project_id: string;
        };
        Insert: {
          experience_id: string;
          project_id: string;
        };
        Update: {
          experience_id?: string;
          project_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'experience_projects_experience_id_fkey';
            columns: ['experience_id'];
            isOneToOne: false;
            referencedRelation: 'experiences';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'experience_projects_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      experience_technologies: {
        Row: {
          experience_id: string;
          technology_id: string;
        };
        Insert: {
          experience_id: string;
          technology_id: string;
        };
        Update: {
          experience_id?: string;
          technology_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'experience_technologies_experience_id_fkey';
            columns: ['experience_id'];
            isOneToOne: false;
            referencedRelation: 'experiences';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'experience_technologies_technology_id_fkey';
            columns: ['technology_id'];
            isOneToOne: false;
            referencedRelation: 'technologies';
            referencedColumns: ['id'];
          },
        ];
      };
      experiences: {
        Row: {
          created_at: string;
          current: boolean;
          description_markdown: string | null;
          end_date: string | null;
          id: string;
          organization: string;
          organization_url: string | null;
          position: string;
          sort_order: number;
          start_date: string;
          summary: string | null;
          updated_at: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          current?: boolean;
          description_markdown?: string | null;
          end_date?: string | null;
          id?: string;
          organization: string;
          organization_url?: string | null;
          position: string;
          sort_order?: number;
          start_date: string;
          summary?: string | null;
          updated_at?: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          current?: boolean;
          description_markdown?: string | null;
          end_date?: string | null;
          id?: string;
          organization?: string;
          organization_url?: string | null;
          position?: string;
          sort_order?: number;
          start_date?: string;
          summary?: string | null;
          updated_at?: string;
          visible?: boolean;
        };
        Relationships: [];
      };
      impact_metrics: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          label: string;
          sort_order: number;
          updated_at: string;
          value: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          label: string;
          sort_order?: number;
          updated_at?: string;
          value: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          label?: string;
          sort_order?: number;
          updated_at?: string;
          value?: string;
          visible?: boolean;
        };
        Relationships: [];
      };
      media_assets: {
        Row: {
          alt_text: string | null;
          caption: string | null;
          category: string;
          created_at: string;
          created_by: string | null;
          decorative: boolean;
          file_size: number;
          filename: string;
          height: number | null;
          id: string;
          mime_type: string;
          public_url: string | null;
          storage_bucket: string;
          storage_object_id: string;
          storage_path: string;
          updated_at: string;
          visibility: string;
          width: number | null;
        };
        Insert: {
          alt_text?: string | null;
          caption?: string | null;
          category?: string;
          created_at?: string;
          created_by?: string | null;
          decorative?: boolean;
          file_size: number;
          filename: string;
          height?: number | null;
          id?: string;
          mime_type: string;
          public_url?: string | null;
          storage_bucket: string;
          storage_object_id: string;
          storage_path: string;
          updated_at?: string;
          visibility?: string;
          width?: number | null;
        };
        Update: {
          alt_text?: string | null;
          caption?: string | null;
          category?: string;
          created_at?: string;
          created_by?: string | null;
          decorative?: boolean;
          file_size?: number;
          filename?: string;
          height?: number | null;
          id?: string;
          mime_type?: string;
          public_url?: string | null;
          storage_bucket?: string;
          storage_object_id?: string;
          storage_path?: string;
          updated_at?: string;
          visibility?: string;
          width?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'media_assets_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'admin_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      media_references: {
        Row: {
          asset_id: string;
          created_at: string;
          document_id: string | null;
          entity_id: string | null;
          entity_type: string | null;
          field: string;
          id: string;
          post_id: string | null;
          project_id: string | null;
          project_image_id: string | null;
          settings_id: string | null;
          technology_id: string | null;
        };
        Insert: {
          asset_id: string;
          created_at?: string;
          document_id?: string | null;
          entity_id?: string | null;
          entity_type?: string | null;
          field: string;
          id?: string;
          post_id?: string | null;
          project_id?: string | null;
          project_image_id?: string | null;
          settings_id?: string | null;
          technology_id?: string | null;
        };
        Update: {
          asset_id?: string;
          created_at?: string;
          document_id?: string | null;
          entity_id?: string | null;
          entity_type?: string | null;
          field?: string;
          id?: string;
          post_id?: string | null;
          project_id?: string | null;
          project_image_id?: string | null;
          settings_id?: string | null;
          technology_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'media_references_asset_id_fkey';
            columns: ['asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_references_document_id_fkey';
            columns: ['document_id'];
            isOneToOne: false;
            referencedRelation: 'documents';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_references_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_references_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_references_project_image_id_fkey';
            columns: ['project_image_id'];
            isOneToOne: false;
            referencedRelation: 'project_images';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_references_settings_id_fkey';
            columns: ['settings_id'];
            isOneToOne: false;
            referencedRelation: 'site_settings';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_references_technology_id_fkey';
            columns: ['technology_id'];
            isOneToOne: false;
            referencedRelation: 'technologies';
            referencedColumns: ['id'];
          },
        ];
      };
      post_categories: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          name: string;
          slug: string;
          sort_order: number;
          updated_at: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          name: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          name?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
          visible?: boolean;
        };
        Relationships: [];
      };
      post_category_relations: {
        Row: {
          category_id: string;
          post_id: string;
        };
        Insert: {
          category_id: string;
          post_id: string;
        };
        Update: {
          category_id?: string;
          post_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'post_category_relations_category_id_fkey';
            columns: ['category_id'];
            isOneToOne: false;
            referencedRelation: 'post_categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'post_category_relations_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
        ];
      };
      post_tags: {
        Row: {
          post_id: string;
          tag_id: string;
        };
        Insert: {
          post_id: string;
          tag_id: string;
        };
        Update: {
          post_id?: string;
          tag_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'post_tags_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'post_tags_tag_id_fkey';
            columns: ['tag_id'];
            isOneToOne: false;
            referencedRelation: 'tags';
            referencedColumns: ['id'];
          },
        ];
      };
      posts: {
        Row: {
          canonical_url: string | null;
          content_markdown: string;
          created_at: string;
          excerpt: string | null;
          featured: boolean;
          featured_image_asset_id: string | null;
          featured_image_url: string | null;
          id: string;
          og_image_asset_id: string | null;
          og_image_url: string | null;
          popular_rank: number | null;
          published_at: string | null;
          reading_time: number | null;
          robots_policy: string | null;
          seo_description: string | null;
          seo_title: string | null;
          slug: string;
          status: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          canonical_url?: string | null;
          content_markdown?: string;
          created_at?: string;
          excerpt?: string | null;
          featured?: boolean;
          featured_image_asset_id?: string | null;
          featured_image_url?: string | null;
          id?: string;
          og_image_asset_id?: string | null;
          og_image_url?: string | null;
          popular_rank?: number | null;
          published_at?: string | null;
          reading_time?: number | null;
          robots_policy?: string | null;
          seo_description?: string | null;
          seo_title?: string | null;
          slug: string;
          status?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          canonical_url?: string | null;
          content_markdown?: string;
          created_at?: string;
          excerpt?: string | null;
          featured?: boolean;
          featured_image_asset_id?: string | null;
          featured_image_url?: string | null;
          id?: string;
          og_image_asset_id?: string | null;
          og_image_url?: string | null;
          popular_rank?: number | null;
          published_at?: string | null;
          reading_time?: number | null;
          robots_policy?: string | null;
          seo_description?: string | null;
          seo_title?: string | null;
          slug?: string;
          status?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'posts_featured_image_asset_id_fkey';
            columns: ['featured_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'posts_og_image_asset_id_fkey';
            columns: ['og_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
        ];
      };
      project_challenges: {
        Row: {
          created_at: string;
          id: string;
          problem: string | null;
          project_id: string;
          solution: string | null;
          sort_order: number;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          problem?: string | null;
          project_id: string;
          solution?: string | null;
          sort_order?: number;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          problem?: string | null;
          project_id?: string;
          solution?: string | null;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'project_challenges_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      project_features: {
        Row: {
          created_at: string;
          description: string | null;
          icon: string | null;
          id: string;
          project_id: string;
          sort_order: number;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          icon?: string | null;
          id?: string;
          project_id: string;
          sort_order?: number;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          icon?: string | null;
          id?: string;
          project_id?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'project_features_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      project_images: {
        Row: {
          alt_text: string;
          asset_id: string;
          caption: string | null;
          created_at: string;
          featured: boolean;
          id: string;
          project_id: string;
          public_url: string | null;
          sort_order: number;
          storage_path: string;
          updated_at: string;
        };
        Insert: {
          alt_text: string;
          asset_id: string;
          caption?: string | null;
          created_at?: string;
          featured?: boolean;
          id?: string;
          project_id: string;
          public_url?: string | null;
          sort_order?: number;
          storage_path: string;
          updated_at?: string;
        };
        Update: {
          alt_text?: string;
          asset_id?: string;
          caption?: string | null;
          created_at?: string;
          featured?: boolean;
          id?: string;
          project_id?: string;
          public_url?: string | null;
          sort_order?: number;
          storage_path?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'project_images_asset_id_fkey';
            columns: ['asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'project_images_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      project_metrics: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          label: string;
          project_id: string;
          sort_order: number;
          updated_at: string;
          value: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          label: string;
          project_id: string;
          sort_order?: number;
          updated_at?: string;
          value: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          label?: string;
          project_id?: string;
          sort_order?: number;
          updated_at?: string;
          value?: string;
          visible?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'project_metrics_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      project_technologies: {
        Row: {
          project_id: string;
          sort_order: number;
          technology_id: string;
        };
        Insert: {
          project_id: string;
          sort_order?: number;
          technology_id: string;
        };
        Update: {
          project_id?: string;
          sort_order?: number;
          technology_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'project_technologies_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'project_technologies_technology_id_fkey';
            columns: ['technology_id'];
            isOneToOne: false;
            referencedRelation: 'technologies';
            referencedColumns: ['id'];
          },
        ];
      };
      projects: {
        Row: {
          after_markdown: string | null;
          architecture: string | null;
          before_markdown: string | null;
          canonical_url: string | null;
          challenges: string | null;
          cover_image_asset_id: string | null;
          cover_image_url: string | null;
          created_at: string;
          demo_url: string | null;
          documentation_url: string | null;
          featured: boolean;
          featured_image_asset_id: string | null;
          featured_image_url: string | null;
          github_url: string | null;
          id: string;
          learnings: string | null;
          objective: string | null;
          og_image_asset_id: string | null;
          og_image_url: string | null;
          problem: string | null;
          published: boolean;
          published_at: string | null;
          robots_policy: string | null;
          role: string | null;
          seo_description: string | null;
          seo_title: string | null;
          slug: string;
          solution: string | null;
          sort_order: number;
          status: string;
          subtitle: string | null;
          summary: string | null;
          title: string;
          updated_at: string;
          year: number | null;
        };
        Insert: {
          after_markdown?: string | null;
          architecture?: string | null;
          before_markdown?: string | null;
          canonical_url?: string | null;
          challenges?: string | null;
          cover_image_asset_id?: string | null;
          cover_image_url?: string | null;
          created_at?: string;
          demo_url?: string | null;
          documentation_url?: string | null;
          featured?: boolean;
          featured_image_asset_id?: string | null;
          featured_image_url?: string | null;
          github_url?: string | null;
          id?: string;
          learnings?: string | null;
          objective?: string | null;
          og_image_asset_id?: string | null;
          og_image_url?: string | null;
          problem?: string | null;
          published?: boolean;
          published_at?: string | null;
          robots_policy?: string | null;
          role?: string | null;
          seo_description?: string | null;
          seo_title?: string | null;
          slug: string;
          solution?: string | null;
          sort_order?: number;
          status?: string;
          subtitle?: string | null;
          summary?: string | null;
          title: string;
          updated_at?: string;
          year?: number | null;
        };
        Update: {
          after_markdown?: string | null;
          architecture?: string | null;
          before_markdown?: string | null;
          canonical_url?: string | null;
          challenges?: string | null;
          cover_image_asset_id?: string | null;
          cover_image_url?: string | null;
          created_at?: string;
          demo_url?: string | null;
          documentation_url?: string | null;
          featured?: boolean;
          featured_image_asset_id?: string | null;
          featured_image_url?: string | null;
          github_url?: string | null;
          id?: string;
          learnings?: string | null;
          objective?: string | null;
          og_image_asset_id?: string | null;
          og_image_url?: string | null;
          problem?: string | null;
          published?: boolean;
          published_at?: string | null;
          robots_policy?: string | null;
          role?: string | null;
          seo_description?: string | null;
          seo_title?: string | null;
          slug?: string;
          solution?: string | null;
          sort_order?: number;
          status?: string;
          subtitle?: string | null;
          summary?: string | null;
          title?: string;
          updated_at?: string;
          year?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'projects_cover_image_asset_id_fkey';
            columns: ['cover_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'projects_featured_image_asset_id_fkey';
            columns: ['featured_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'projects_og_image_asset_id_fkey';
            columns: ['og_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
        ];
      };
      site_builds: {
        Row: {
          commit_sha: string | null;
          completed_at: string | null;
          content_snapshot_hash: string | null;
          created_at: string;
          deployment_id: string | null;
          entity_id: string | null;
          entity_type: string | null;
          failure_reason: string | null;
          github_run_attempt: number | null;
          github_run_id: number | null;
          github_run_url: string | null;
          id: string;
          request_id: string;
          retry_of: string | null;
          started_at: string | null;
          status: string;
          trigger_type: string;
          updated_at: string;
        };
        Insert: {
          commit_sha?: string | null;
          completed_at?: string | null;
          content_snapshot_hash?: string | null;
          created_at?: string;
          deployment_id?: string | null;
          entity_id?: string | null;
          entity_type?: string | null;
          failure_reason?: string | null;
          github_run_attempt?: number | null;
          github_run_id?: number | null;
          github_run_url?: string | null;
          id?: string;
          request_id: string;
          retry_of?: string | null;
          started_at?: string | null;
          status?: string;
          trigger_type: string;
          updated_at?: string;
        };
        Update: {
          commit_sha?: string | null;
          completed_at?: string | null;
          content_snapshot_hash?: string | null;
          created_at?: string;
          deployment_id?: string | null;
          entity_id?: string | null;
          entity_type?: string | null;
          failure_reason?: string | null;
          github_run_attempt?: number | null;
          github_run_id?: number | null;
          github_run_url?: string | null;
          id?: string;
          request_id?: string;
          retry_of?: string | null;
          started_at?: string | null;
          status?: string;
          trigger_type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'site_builds_retry_of_fkey';
            columns: ['retry_of'];
            isOneToOne: false;
            referencedRelation: 'site_builds';
            referencedColumns: ['id'];
          },
        ];
      };
      site_settings: {
        Row: {
          about_image_asset_id: string | null;
          about_profile_markdown: string | null;
          about_summary_markdown: string | null;
          availability_enabled: boolean;
          availability_text: string | null;
          brand_short: string;
          canonical_base: string | null;
          created_at: string;
          cv_url: string | null;
          default_og_image: string | null;
          default_og_image_asset_id: string | null;
          default_seo_description: string | null;
          default_seo_title: string | null;
          hero_description: string | null;
          hero_subtitle: string | null;
          hero_title: string | null;
          id: string;
          location_public: string | null;
          professional_title: string | null;
          robots_policy: string;
          singleton: boolean;
          site_name: string;
          timezone: string;
          updated_at: string;
          working_method_markdown: string | null;
        };
        Insert: {
          about_image_asset_id?: string | null;
          about_profile_markdown?: string | null;
          about_summary_markdown?: string | null;
          availability_enabled?: boolean;
          availability_text?: string | null;
          brand_short: string;
          canonical_base?: string | null;
          created_at?: string;
          cv_url?: string | null;
          default_og_image?: string | null;
          default_og_image_asset_id?: string | null;
          default_seo_description?: string | null;
          default_seo_title?: string | null;
          hero_description?: string | null;
          hero_subtitle?: string | null;
          hero_title?: string | null;
          id?: string;
          location_public?: string | null;
          professional_title?: string | null;
          robots_policy?: string;
          singleton?: boolean;
          site_name: string;
          timezone?: string;
          updated_at?: string;
          working_method_markdown?: string | null;
        };
        Update: {
          about_image_asset_id?: string | null;
          about_profile_markdown?: string | null;
          about_summary_markdown?: string | null;
          availability_enabled?: boolean;
          availability_text?: string | null;
          brand_short?: string;
          canonical_base?: string | null;
          created_at?: string;
          cv_url?: string | null;
          default_og_image?: string | null;
          default_og_image_asset_id?: string | null;
          default_seo_description?: string | null;
          default_seo_title?: string | null;
          hero_description?: string | null;
          hero_subtitle?: string | null;
          hero_title?: string | null;
          id?: string;
          location_public?: string | null;
          professional_title?: string | null;
          robots_policy?: string;
          singleton?: boolean;
          site_name?: string;
          timezone?: string;
          updated_at?: string;
          working_method_markdown?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'site_settings_about_image_asset_id_fkey';
            columns: ['about_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'site_settings_default_og_image_asset_id_fkey';
            columns: ['default_og_image_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
        ];
      };
      social_links: {
        Row: {
          created_at: string;
          icon: string | null;
          id: string;
          label: string;
          platform: string;
          sort_order: number;
          updated_at: string;
          url: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          icon?: string | null;
          id?: string;
          label: string;
          platform: string;
          sort_order?: number;
          updated_at?: string;
          url: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          icon?: string | null;
          id?: string;
          label?: string;
          platform?: string;
          sort_order?: number;
          updated_at?: string;
          url?: string;
          visible?: boolean;
        };
        Relationships: [];
      };
      specialties: {
        Row: {
          created_at: string;
          description: string | null;
          icon: string | null;
          id: string;
          slug: string;
          sort_order: number;
          title: string;
          updated_at: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          icon?: string | null;
          id?: string;
          slug: string;
          sort_order?: number;
          title: string;
          updated_at?: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          icon?: string | null;
          id?: string;
          slug?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
          visible?: boolean;
        };
        Relationships: [];
      };
      tags: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          slug: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          slug: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          slug?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      technologies: {
        Row: {
          category: string;
          created_at: string;
          description: string | null;
          featured: boolean;
          icon: string | null;
          icon_asset_id: string | null;
          icon_url: string | null;
          id: string;
          name: string;
          official_url: string | null;
          slug: string;
          sort_order: number;
          updated_at: string;
          visible: boolean;
        };
        Insert: {
          category: string;
          created_at?: string;
          description?: string | null;
          featured?: boolean;
          icon?: string | null;
          icon_asset_id?: string | null;
          icon_url?: string | null;
          id?: string;
          name: string;
          official_url?: string | null;
          slug: string;
          sort_order?: number;
          updated_at?: string;
          visible?: boolean;
        };
        Update: {
          category?: string;
          created_at?: string;
          description?: string | null;
          featured?: boolean;
          icon?: string | null;
          icon_asset_id?: string | null;
          icon_url?: string | null;
          id?: string;
          name?: string;
          official_url?: string | null;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
          visible?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'technologies_icon_asset_id_fkey';
            columns: ['icon_asset_id'];
            isOneToOne: false;
            referencedRelation: 'media_assets';
            referencedColumns: ['id'];
          },
        ];
      };
      work_principles: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          number: number;
          sort_order: number;
          title: string;
          updated_at: string;
          visible: boolean;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          number: number;
          sort_order?: number;
          title: string;
          updated_at?: string;
          visible?: boolean;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          number?: number;
          sort_order?: number;
          title?: string;
          updated_at?: string;
          visible?: boolean;
        };
        Relationships: [];
      };
    };
    Views: {
      admin_analytics_daily_dimensions: {
        Row: {
          article_shares: number | null;
          contact_submits: number | null;
          cv_downloads: number | null;
          date: string | null;
          demo_clicks: number | null;
          dimension: string | null;
          email_clicks: number | null;
          email_copies: number | null;
          github_clicks: number | null;
          linkedin_clicks: number | null;
          page_views: number | null;
          post_views: number | null;
          project_views: number | null;
          unique_sessions: number | null;
          value: string | null;
          whatsapp_clicks: number | null;
        };
        Insert: {
          article_shares?: number | null;
          contact_submits?: number | null;
          cv_downloads?: number | null;
          date?: string | null;
          demo_clicks?: number | null;
          dimension?: string | null;
          email_clicks?: number | null;
          email_copies?: number | null;
          github_clicks?: number | null;
          linkedin_clicks?: number | null;
          page_views?: number | null;
          post_views?: number | null;
          project_views?: number | null;
          unique_sessions?: number | null;
          value?: string | null;
          whatsapp_clicks?: number | null;
        };
        Update: {
          article_shares?: number | null;
          contact_submits?: number | null;
          cv_downloads?: number | null;
          date?: string | null;
          demo_clicks?: number | null;
          dimension?: string | null;
          email_clicks?: number | null;
          email_copies?: number | null;
          github_clicks?: number | null;
          linkedin_clicks?: number | null;
          page_views?: number | null;
          post_views?: number | null;
          project_views?: number | null;
          unique_sessions?: number | null;
          value?: string | null;
          whatsapp_clicks?: number | null;
        };
        Relationships: [];
      };
      admin_analytics_daily_sessions: {
        Row: {
          content_id: string | null;
          content_type: string | null;
          date: string | null;
          id: string | null;
          session_hash: string | null;
        };
        Insert: {
          content_id?: string | null;
          content_type?: string | null;
          date?: string | null;
          id?: string | null;
          session_hash?: string | null;
        };
        Update: {
          content_id?: string | null;
          content_type?: string | null;
          date?: string | null;
          id?: string | null;
          session_hash?: string | null;
        };
        Relationships: [];
      };
      public_contact_settings: {
        Row: {
          cta_description: string | null;
          cta_title: string | null;
          cv_enabled: boolean | null;
          email: string | null;
          email_visible: boolean | null;
          form_enabled: boolean | null;
          id: string | null;
          whatsapp_cta_label: string | null;
          whatsapp_default_message: string | null;
          whatsapp_number: string | null;
          whatsapp_visible: boolean | null;
        };
        Relationships: [];
      };
      public_media_assets: {
        Row: {
          alt_text: string | null;
          caption: string | null;
          category: string | null;
          decorative: boolean | null;
          file_size: number | null;
          filename: string | null;
          height: number | null;
          id: string | null;
          mime_type: string | null;
          public_url: string | null;
          visibility: string | null;
          width: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      activate_cv: { Args: { document_id: string }; Returns: undefined };
      edge_dispatch_failed: {
        Args: { p_build_id: string; p_reason: string };
        Returns: undefined;
      };
      edge_record_contact: {
        Args: {
          p_email: string;
          p_global_hash: string;
          p_global_limit?: number;
          p_message: string;
          p_name: string;
          p_notify?: boolean;
          p_origin_hash: string;
          p_session_hash: string;
          p_subject: string;
          p_submission_id: string;
        };
        Returns: Json;
      };
      edge_record_event: {
        Args: {
          p_browser?: string;
          p_device?: string;
          p_event_id: string;
          p_event_type: string;
          p_global_hash: string;
          p_origin_hash: string;
          p_pathname: string;
          p_post_id?: string;
          p_project_id?: string;
          p_referrer?: string;
          p_session_hash: string;
        };
        Returns: Json;
      };
      edge_request_build: {
        Args: {
          p_actor: string;
          p_entity_id?: string;
          p_entity_type?: string;
          p_request_id: string;
          p_retry_of?: string;
          p_trigger: string;
        };
        Returns: Json;
      };
      edge_update_build_status: {
        Args: {
          p_build_id: string;
          p_commit_sha: string;
          p_completed_at?: string;
          p_deployment_id?: string;
          p_failure_reason?: string;
          p_run_attempt: number;
          p_run_id: number;
          p_run_url: string;
          p_started_at: string;
          p_status: string;
        };
        Returns: Json;
      };
      get_analytics_report: {
        Args: { p_from: string; p_to: string };
        Returns: Json;
      };
      get_public_snapshot: { Args: never; Returns: Json };
      maintain_analytics: { Args: never; Returns: undefined };
      refresh_analytics: {
        Args: { p_from?: string; p_to?: string };
        Returns: undefined;
      };
      replace_media_asset: {
        Args: {
          expected_updated_at: string;
          previous_id: string;
          replacement_id: string;
        };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  private: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const;
