import type { Options as Schema } from 'rehype-sanitize';

/** Only application-generated attributes survive. Raw authored HTML is discarded upstream. */
export const editorialSchema: Schema = {
  tagNames: [
    'p',
    'br',
    'hr',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'strong',
    'em',
    'del',
    'a',
    'ul',
    'ol',
    'li',
    'blockquote',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
    'pre',
    'code',
    'span',
    'figure',
    'figcaption',
    'picture',
    'source',
    'img',
    'div',
  ],
  attributes: {
    a: ['href', 'title', 'rel', 'target'],
    h2: ['id'],
    h3: ['id'],
    h4: ['id'],
    h5: ['id'],
    h6: ['id'],
    img: ['src', 'alt', 'width', 'height', 'loading', 'decoding'],
    source: ['type', 'srcSet', 'sizes'],
    pre: ['tabIndex', 'ariaLabel', 'role'],
    div: [['className', 'table-scroll'], 'tabIndex', 'role', 'ariaLabel'],
    figure: [['className', 'code-block']],
    code: [['className', 'numbered']],
    span: [['className', 'code-line', 'syntax-keyword', 'syntax-string', 'syntax-comment']],
    th: ['align', 'scope'],
    td: ['align'],
    ol: ['start'],
  },
  protocols: { href: ['https'], src: [], srcSet: [] },
  clobber: ['id', 'name'],
  clobberPrefix: 'content-',
};
