import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

export const baselineVersion = '20260906001900';
export const baselineName = baselineVersion + '_initial_portfolio.sql';
export const archive = new URL('../supabase/legacy-migrations/', import.meta.url);
export const manifest = JSON.parse(readFileSync(new URL('manifest.json', archive), 'utf8'));
export const hash = (text) => createHash('sha256').update(text).digest('hex');
export const normalize = (text) => text.replaceAll('\r\n', '\n');

export function historicalSources() {
  if (manifest.sources.length !== 18) throw new Error('Expected 18 immutable source migrations.');
  return manifest.sources.map((source) => {
    const sql = normalize(readFileSync(new URL(source.file, archive), 'utf8'));
    if (hash(sql) !== source.sha256)
      throw new Error('Historical migration changed: ' + source.file);
    return { ...source, sql };
  });
}

function removeExactly(sql, text) {
  if (sql.split(text).length !== 2) throw new Error('Baseline transformation no longer matches.');
  return sql.replace(text, () => '');
}

export function generateBaseline(sources = historicalSources()) {
  const sections = sources.map(({ file, sql }) => {
    // Strip only the verified outer transaction; PL/pgSQL BEGIN blocks remain intact.
    if (!/^(?:--[^\n]*\n)*begin;\n/i.test(sql) || !/commit;\s*$/i.test(sql))
      throw new Error('Unexpected migration transaction envelope: ' + file);
    let body = sql.replace(/^(?:--[^\n]*\n)*begin;\n/i, '').replace(/commit;\s*$/i, '');
    if (file === '20260906001400_storage_buckets.sql') {
      body = removeExactly(
        body,
        '-- A tracked object cannot be deleted through Storage, even if the caller skips the UI.\n' +
          '-- PostgreSQL enforces this FK under every role and locks concurrent registrations/deletes.\n' +
          'alter table public.media_assets add constraint media_assets_storage_object_fk\n' +
          ' foreign key(storage_bucket,storage_path) references storage.objects(bucket_id,name) on delete restrict on update restrict;\n' +
          'comment on constraint media_assets_storage_object_fk on public.media_assets is\n' +
          " 'F8 depends on the managed Storage bucket/name unique key. Verify on platform upgrades. Delete metadata only after unlinking, then remove bytes.';\n",
      );
    }
    if (file === '20260906001800_storage_object_identity.sql') {
      body = removeExactly(
        body,
        '-- Own-table lock: keep the old FK protecting all objects throughout the backfill.\n' +
          'lock table public.media_assets in access exclusive mode;\n',
      );
      body = removeExactly(
        body,
        'update public.media_assets a set storage_object_id = o.id\n' +
          'from storage.objects o\n' +
          'where a.storage_bucket = o.bucket_id and a.storage_path = o.name;\n' +
          '-- Fail atomically if legacy data cannot be resolved; never discard metadata.\n',
      );
      body = removeExactly(
        body,
        '-- Only remove our non-PK dependency after the replacement has been validated.\n' +
          'alter table public.media_assets drop constraint media_assets_storage_object_fk;\n',
      );
    }
    return '-- Source: legacy-migrations/' + file + '\n' + body.trim() + '\n';
  });
  return `-- Generated by npm run db:baseline:generate. Do not edit this artifact.
-- Immutable sources, hashes and transformations: scripts/baseline-model.mjs.
-- Empty installation only; existing F8 databases must follow the verified adoption procedure.
begin;
do $baseline_guard$
begin
  if to_regnamespace('private') is not null
    or exists (select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace
      where n.nspname='public' and c.relkind in ('r','p','v','m','S','f'))
    or exists (select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace
      where n.nspname='public' and p.proname <> 'rls_auto_enable')
    or exists (select 1 from storage.buckets)
    or exists (select 1 from storage.objects)
  then
    raise exception 'Initial baseline requires an empty application; use the existing-database adoption procedure';
  end if;
end;
$baseline_guard$;

${sections.join('\n')}
commit;
`;
}
